web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php-fpm
php-fpm:
    image: php:7.2-fpm
    volumes:
        - ./code:/code